feat: add graphql
jonowu/sustainability-app-demo pull request #15
Opened 2020-08-21 06:25 UTC by jonowu

## Purpose

Refactor the app to use graphql.

## Changes

You will need to run `npm install` when testing this branch.
You can test graphql queries here: http://sa4si-admin.herokuapp.com/graphql

## Checklist

- [ ] Tested on Android
- [ ] Tested on iOS

2020-08-21 06:25 UTC, jonowu commented on utils/apolloClient.js
> +  const token = await AsyncStorage.getItem('token');
Pulls the bearer token from async storage

2020-08-21 06:27 UTC, jonowu commented on screens/sdgs/index.js
> +  });
This combines the local array of sdg objects with the data from strapi (where they have the same sdg number/id).

2020-08-21 06:28 UTC, jonowu commented on screens/action/index.js
> +      createEntry(input: { data: { action: ${id}, user: ${userId} } }) {
A mutation is like a post request. Here, we create a new entry that includes the action and user as data.

2020-08-21 06:29 UTC, jonowu commented on screens/actions/index.js
> +    query GetUserActions {
This query gets the all the actions, and entries that the currently logged in user has submitted. This an advantage of graphql; we can query multiple datasets in a single request.

2020-08-21 06:30 UTC, jonowu commented on screens/news/index.js
> +      articles {
This query simply gets all the articles, with only the relevant data that we need. This is a big advantage of graphql; we only get back the data we ask for.

2020-08-27 06:00 UTC, BenjaminYong requested changes
Looks good, works well on my phone.
Can only suggest a screen or styling to center the loading indicators 👍

2020-08-31 15:06 UTC, merged